-- Full Schema Migration Script for New Supabase Project
-- Generated based on inspection of Old Database and existing SQL files.

-- 1. Create manpower_requests table
CREATE TABLE IF NOT EXISTS manpower_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    division TEXT,
    position TEXT,
    job_description TEXT,
    requirements TEXT,
    quantity INTEGER,
    status TEXT,
    priority TEXT,
    requester_name TEXT,
    rejection_reason TEXT,
    user_id BIGINT,
    approved_at TIMESTAMP WITH TIME ZONE,
    finalized_at TIMESTAMP WITH TIME ZONE,
    hire_purpose TEXT,
    position_level TEXT,
    education_qualification TEXT,
    years_of_experience TEXT,
    other_qualifications TEXT
);

-- 2. Create job_vacancies table
CREATE TABLE IF NOT EXISTS job_vacancies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    manpower_request_id BIGINT REFERENCES manpower_requests(id),
    title TEXT NOT NULL,
    description TEXT,
    requirements TEXT,
    location TEXT DEFAULT 'Head Office',
    type TEXT DEFAULT 'Full-time',
    salary_range TEXT,
    posted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    views_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vacancies_active ON job_vacancies(is_active, expires_at);

-- 3. Create candidates table
CREATE TABLE IF NOT EXISTS candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    full_name TEXT,
    email TEXT,
    phone TEXT,
    position TEXT, -- Position applied for
    cv_url TEXT,
    photo_url TEXT,
    cv_text TEXT,
    status TEXT DEFAULT 'New', -- e.g., New, Screening, Interview, Rejected, Hired
    religion TEXT,
    blood_type TEXT,
    address TEXT,
    cv_drive_id TEXT, -- ID from Google Drive if used
    request_id BIGINT, -- Potentially links to manpower_request_id
    biggest_achievement TEXT,
    strengths JSONB DEFAULT '[]'::jsonb,
    weaknesses JSONB DEFAULT '[]'::jsonb,
    nik TEXT,
    sim_ownership TEXT,
    sim_number TEXT,
    medical_history TEXT,
    experience JSONB DEFAULT '[]'::jsonb,
    education JSONB DEFAULT '[]'::jsonb
);

-- 4. Enable Row Level Security (RLS) - Optional but recommended (Standard Supabase setup)
ALTER TABLE manpower_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_vacancies ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Permissive for now to match "local" feel, but normally you want strict policies)
-- WARNING: These policies allow public read/write. Adjust as needed for production security.
-- Since the user said "same settings", and we don't know the old policies, we will ALLOW ALL for anon/service_role to ensure it "just works".
-- User should refine this later.

CREATE POLICY "Enable all access for all users" ON manpower_requests FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON job_vacancies FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON candidates FOR ALL USING (true);
