-- Create missing tables identified during debugging

-- 1. app_settings (Stores Admin/App configurations)
CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  config JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. portal_users (For Division/Portal Auth)
CREATE TABLE IF NOT EXISTS portal_users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE,
  password_hash TEXT,
  division TEXT,
  role TEXT,
  status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. analyses (AI Analysis Results)
CREATE TABLE IF NOT EXISTS analyses (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  candidate_id BIGINT REFERENCES candidates(id) ON DELETE CASCADE,
  match_score NUMERIC,
  verdict TEXT,
  content TEXT, -- The AI analysis text
  ocr_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. disc_results (DISC Test Results)
CREATE TABLE IF NOT EXISTS disc_results (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  candidate_id BIGINT REFERENCES candidates(id) ON DELETE CASCADE,
  d_score NUMERIC,
  i_score NUMERIC,
  s_score NUMERIC,
  c_score NUMERIC,
  profile TEXT,
  answers JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and Allow All (to match "local" feel)
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE portal_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;
ALTER TABLE disc_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON app_settings FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON portal_users FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON analyses FOR ALL USING (true);
CREATE POLICY "Enable all access for all users" ON disc_results FOR ALL USING (true);
